version: 0.0
os: linux
files:
  - source: /target/awsHelloWorld.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/uninstall_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root