version: 0.0
os: linux
files:
  - source: /awsHelloWorld.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: ./stop_application.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: ./uninstall_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./start_application.sh
      timeout: 300
      runas: root